name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - sandbox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Step 2: Initialize and update submodules
      - name: Initialize and update submodules
        run: git submodule update --init --recursive

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
